## do not remove or change '%s' as these are needed to insert the warp names and config options
localisation:
  plugin_name: DiscoverWarps
  ## config messages
  config: was set to %s
  ## command messages
  commands:
    help: Help
    permission: You do not have permission to run that command!
    arguments: Not enough command arguments!
    not_plate: You are not standing on a pressure plate
    name_in_use: That name is already in use!
    no_plate_name: Couldn't find a DiscoverPlate with that name!
    no_player: There is no player with that name online!
    only_player: This command requires a player!
    cost: The last argument must be a number!
    none_set: There are no DiscoverPlates to find!
    no_warp_name: You need to supply a warp name!
    no_warp_cooldown: You need to wait %s seconds before warping again.
    needs_discover: You need to discover %s before you can teleport to it!
    auto_discover: DiscoverPlate %s auto-discovery is
    added: DiscoverPlate %s added!
    enabled: DiscoverPlate %s enabled!
    disabled: DiscoverPlate %s disabled!
    deleted: DiscoverPlate %s deleted!
    renamed: DiscoverPlate %s renamed to %s!
    no_material: Invalid material specified!
    icon: DiscoverPlate icon set!
    str_true: true
    str_false: false
    restart: A server restart will be needed in order to hook %s into your economy plugin
  ## buying messages
  buying:
    no_buying: You are not allowed to buy DiscoverWarps on this server!
    cannot_buy: You cannot buy the location of DiscoverPlate %s!
    no_money: You don't have enough money to use this sign!
    no_need: You have already discovered %s!
    bought: You bought the DiscoverPlate location %s for
  ## general messages
  discovered: You have discovered %s
  teleport: Teleporting
  list: List
  visited: VISITED
  not_visited: NOT VISITED
  auto: AUTO
  no_break: You cannot break this pressure plate, use %s to remove it.
  region_found: WorldGuard region '%s' found, region detection will be enabled for this pressure plate.
  ## help messages
  help:
    set: To set a stone or wood pressure plate as a DiscoverPlate, stand on it and then type
    delete: To delete a DiscoverPlate type
    rename: To rename a DiscoverPlate type
    icon: To set the DiscoverPlate icon displayed in the GUI
    disable: To disable a DiscoverPlate type
    enable: To enable a DiscoverPlate type
    auto: To make a DiscoverPlate auto-discovered type
    cost: To set a cost to buy a DiscoverPlate location type
    list: To list DiscoverPlates type
    warp: To warp to a DiscoverPlate type
    buy: To buy a DiscoverPlate location type
    config: To toggle DiscoverWarps config settings type
  ## sign messages
  signs:
    no_money: You don't have enough maney to use this sign!
    needs_discover: You have not discovered %s yet!
    sign_made: Sign set successfully!
    sign_permission: You do not have permission to make a DiscoverWarps sign!
no_damage: false
no_damage_time: 10
allow_buying: false
xp_on_discover: false
xp_to_give: 3
sign: discoverwarp
worldguard_regions: true
cooldown: 30
debug: false
uuid_conversion_done: true
